# Generated by Django 4.2.3 on 2023-07-23 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fine_tuning_chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finetunedmodel",
            name="file_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="finetunedmodel",
            name="fine_tune_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="finetunedmodel",
            name="fine_tuned_model",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="finetunedmodel",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="finetunedmodel",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fine_tuned_models",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="is_fine_tuned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="training_datas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trainingdata",
            name="will_be_fine_tuned",
            field=models.BooleanField(default=False),
        ),
    ]
